# NUMPY LIBRARY

NumPy stands for `Numerical Python`.

It is an Open Source Python Library used for working with `Arrays`.

In Data Science in general and in Machine Learning in particular we are often working with `2-dimensional Data` consisting of `Rows and Columns`. 

One Way of representing such `Data Matrices` in Python is the `NumPy ndarray Object`.

---

`Import NumPy Library`

In [1]:
import numpy as np

`Creating` **0D-Array** `(Scalar)`

In [3]:
array0D = np.array(0)

print(array0D)
print(type(array0D))

0
<class 'numpy.ndarray'>


`Creating` **1D-Array** `(Row Vector)`

In [308]:
array1D = np.array([0, 1, 1, 0, 0, 0, 1, 0, 0, 1])

print(array1D)
print(type(array1D))

[0 1 1 0 0 0 1 0 0 1]
<class 'numpy.ndarray'>


`Creating` `nx1` **2D-Array** `(Colum Vector)`

In [315]:
array2D_vctr = np.array([0, 1, 1, 0, 0, 0, 1, 0, 0, 1]).reshape(-1,1)

print(array2D_vctr)
print(type(array2D_vctr))

[[0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]]
<class 'numpy.ndarray'>


`Creating` `nxm` **2D-Array** `(Matrix)`

In [313]:
array2D_mtrx = np.array([[0, 1, 1, 0, 0, 0, 1, 0, 0, 1], 
                         [1, 1, 1, 0, 0, 0, 0, 0, 1, 1]])

print(array2D_mtrx)
print(type(array2D_mtrx))

[[0 1 1 0 0 0 1 0 0 1]
 [1 1 1 0 0 0 0 0 1 1]]
<class 'numpy.ndarray'>


`Returning Dimensions of an Array`

In [316]:
# Number of Dimensions
print(array0D.ndim)
print(array1D.ndim)
print(array2D_vctr.ndim)
print(array2D_mtrx.ndim)

0
1
2
2


`Returning Shape of an Array (Dimensions x Elements)`

In [317]:
# Number of Elements per Dimension
print(array0D.shape)
print(array1D.shape)
print(array2D_vctr.shape)
print(array2D_mtrx.shape)

()
(10,)
(10, 1)
(2, 10)


`Returning Size of Array (Total Number of Elements)`

In [318]:
print(array0D.size)
print(array1D.size)
print(array2D_vctr.size)
print(array2D_mtrx.size)

1
10
10
20


`Creating Basic Arrays`

In [328]:
# Array with Zeros
array = np.zeros(5, dtype=np.int64)
print('Row Vector')
print(array)

array = np.zeros((5, 1), dtype=np.int64)
print(' ')
print('Column Vector')
print(array)

array = np.zeros((5, 5), dtype=np.int64)
print(' ')
print('Matrix')
print(array)

Row Vector
[0 0 0 0 0]
 
Column Vector
[[0]
 [0]
 [0]
 [0]
 [0]]
 
Matrix
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [329]:
# Array with Ones
array = np.ones(5, dtype=np.int64)
print('Row Vector')
print(array)

array = np.ones((5, 1), dtype=np.int64)
print(' ')
print('Column Vector')
print(array)

array = np.ones((5, 5), dtype=np.int64)
print(' ')
print('Matrix')
print(array)

Row Vector
[1 1 1 1 1]
 
Column Vector
[[1]
 [1]
 [1]
 [1]
 [1]]
 
Matrix
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [414]:
# Array with Ones on the Diagonal and Zeros else (Eye Matrix)
array = np.eye(10)
print(array)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [338]:
# Array with arranged Values
array = np.arange(1, 11)
print(array)

array = np.arange(2, 11, 2)
print(' ')
print(array)

[ 1  2  3  4  5  6  7  8  9 10]
 
[ 2  4  6  8 10]


In [350]:
# Array with linearly spaced Values 
array = np.linspace(0, 1, 101)
print(array)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


In [591]:
# Array with Random Values between Zero and One
array = np.random.rand(3, 3)
print(array)

[[0.63657321 0.70698231 0.31394033]
 [0.67188712 0.93523601 0.27554403]
 [0.24401704 0.40455125 0.23112864]]


`Accessing` **1D-Arrays** `with [idx]`

`Remember: Index Zero corresponds to the first Element`

In [29]:
array1D = np.array([0, 1, 1, 0, 0, 0, 1, 0, 0, 1])
print(array1D)

[0 1 1 0 0 0 1 0 0 1]


In [30]:
# First Element
print(array1D[0])

0


In [31]:
# Second last Element
print(array1D[-2])

0


In [32]:
# Second to third Element
print(array1D[1:3])

[1 1]


In [33]:
# Fourth last to second last Element
print(array1D[-4:-1])

[1 0 0]


In [34]:
# First to fifth Element
print(array1D[:5])

[0 1 1 0 0]


In [35]:
# Sixth to last Element
print(array1D[5:])

[0 1 0 0 1]


In [49]:
# Every second Element starting with the first Element
print(array1D[::2])

[0 1 0 1 0]


In [50]:
# Every second Element starting with the second Element and ending with the sixth Element
print(array1D[1:6:2])

[1 0 0]


`Accessing` **2D-Arrays** `with [idx1, idx2]`

`Note: idx1 corresponds to the Dimension(s), idx2 to the Element(s) in that Dimension(s)`

In [351]:
array2D = np.array([[0, 1, 1, 0, 0, 0, 1, 0, 0, 1], 
                    [1, 1, 1, 0, 0, 0, 0, 0, 1, 1]])
print(array2D)

[[0 1 1 0 0 0 1 0 0 1]
 [1 1 1 0 0 0 0 0 1 1]]


In [37]:
# First Element in the first Dimension
print(array2D[0, 0])

0


In [39]:
# First Element in the second Dimension
print(array2D[1, 0])

1


In [45]:
# First Element in all Dimensions
print(array2D[:, 0])

[0 1]


In [41]:
# Last four Elements in all Dimensions
print(array2D[:, -4:])

[[1 0 0 1]
 [0 0 1 1]]


In [48]:
# Second, third and last Element in all Dimensions
print(array2D[:, [1, 2, -1]])

[[1 1 1]
 [1 1 1]]


In [51]:
# Every third Element of second Dimension starting with the first Element
print(array2D[1, ::3])

[1 0 0 1]


`Copy vs. View`

In [285]:
# Original Array
array_ori = np.array([1, 2, 3, 4, 5])

# View of Original Array
array_view = array_ori

# Changes on View...
array_view[0] = -99

#...will affect the original Array...
print('Original Array')
print(array_ori)
print('View')
print(array_view)

#...and Changes on original Array...
array_ori[-1] = -99

#...will affect the View
print(' ')
print('Original Array')
print(array_ori)
print('View')
print(array_view)

Original Array
[-99   2   3   4   5]
View
[-99   2   3   4   5]
 
Original Array
[-99   2   3   4 -99]
View
[-99   2   3   4 -99]


In [286]:
array_ori = np.array([1, 2, 3, 4, 5])

# Use "copy()" to avoid such Behavior
array_copy = array_ori.copy()

# Changes on Copy...
array_copy[0] = -99

#...will not affect the original Array
print('Original Array')
print(array_ori)
print('Copy')
print(array_copy)

Original Array
[1 2 3 4 5]
Copy
[-99   2   3   4   5]


`Reshaping Arrays (from` **1D** `to` **2D**`)` using `reshape(rows, columns)`

In [450]:
array1D = np.array([0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1])
print(array1D)
print(array1D.shape)

# Reshape
array2D = array1D.reshape(2, 10)
print(' ')
print('Reshaped Array')
print(array2D)
print('Shape')
print(array2D.shape)

[0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 1]
(20,)
 
Reshaped Array
[[0 1 1 0 0 0 1 0 0 1]
 [1 1 1 0 0 0 0 0 1 1]]
Shape
(2, 10)


`Flattening Arrays (from` **2D** `to` **1D**`)` using `reshape(-1)`

In [448]:
array_flat = array2D.reshape(-1)
print('Flattened Array')
print(array_flat)
print('Shape')
print(array_flat.shape)

Flattened Array
[0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 1]
Shape
(20,)


Or use `flatten` or `ravel` instead

`Note: flatten() returns a Copy, ravel() returns a View`

In [449]:
array_flat = array2D.flatten()
print('Flattened Array')
print(array_flat)
print('Shape')
print(array_flat.shape)

Flattened Array
[0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 1]
Shape
(20,)
[99  1  1  0  0  0  1  0  0  1  1  1  1  0  0  0  0  0  1  1]
[[0 1 1 0 0 0 1 0 0 1]
 [1 1 1 0 0 0 0 0 1 1]]


In [451]:
array_flat = array2D.ravel()
print('Flattened Array')
print(array_flat)
print('Shape')
print(array_flat.shape)

Flattened Array
[0 1 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 1]
Shape
(20,)
[99  1  1  0  0  0  1  0  0  1  1  1  1  0  0  0  0  0  1  1]
[[99  1  1  0  0  0  1  0  0  1]
 [ 1  1  1  0  0  0  0  0  1  1]]


`Transposing Arrays`

In [383]:
array = np.array([[0, 1],
                  [0, 1],
                  [0, 1],
                  [0, 1],
                  [0, 1]])
print(array)
print('Shape:', array.shape)

# Transpose
array_transposed = array.transpose()
print(' ')
print('Transposed Array')
print(array_transposed)
print('Shape:', array_transposed.shape)

# Or use '.T'
array_t = array.T
print(' ')
print('Transposed Array using .T')
print(array_t)
print('Shape:', array_t.shape)

[[0 1]
 [0 1]
 [0 1]
 [0 1]
 [0 1]]
Shape: (5, 2)
 
Transposed Array
[[0 0 0 0 0]
 [1 1 1 1 1]]
Shape: (2, 5)
 
Transposed Array using .T
[[0 0 0 0 0]
 [1 1 1 1 1]]
Shape: (2, 5)


`Flipping Arrays`

In [385]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
print(array)

# Flip
array_flipped = np.flip(array)
print(' ')
print('Flipped Array')
print(array_flipped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
Flipped Array
[[9 8 7]
 [6 5 4]
 [3 2 1]]


`Iterating through` **1D-Array**

In [86]:
# Iterating through Elements of 1D Array
array1D = np.array([1, 2, 3, 4, 5])

for element in array1D:
    print(element)

1
2
3
4
5


`Iterating through` **2D-Array**

In [87]:
# Iterating through Rows of 2D Array
array2D = np.array([[1, 2, 3, 4, 5], 
                    [6, 7, 8, 9, 10]])

for row in array2D:
    print(row)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [88]:
# Iterating through Elements of 2D Array
for row in array2D:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9
10


In [89]:
# Easier with nditer()
for element in np.nditer(array2D):
    print(element)

1
2
3
4
5
6
7
8
9
10


`Joining` **1D-Arrays** using `concatenate`

In [278]:
# Joining 1D-Arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
print(array1)
print(array2)

array_joined = np.concatenate((array1, array2))
print(' ')
print('Joined Array')
print(array_joined)

[1 2 3 4 5]
[ 6  7  8  9 10]
 
Joined Array
[ 1  2  3  4  5  6  7  8  9 10]


`Joining` **2D-Arrays** using `concatenate`

In [115]:
# Joining 2D-Arrays
array1 = np.array([[0, 0], 
                   [0, 0]])

array2 = np.array([[1, 1], 
                   [1, 1]])

print('Array1')
print(array1)
print(' ')
print('Array2')
print(array2)
print(' ')
print('-----------------')

# By Axis 0 (to the Bottom)
array_joined = np.concatenate((array1, array2), axis=0)
print(' ')
print('Joined by Axis 0 (4x2)')
print(array_joined)

# By Axis 1 (to the Right)
array_joined = np.concatenate((array1, array2), axis=1)
print(' ')
print('Joined by Axis 1 (2x4)')
print(array_joined)

Array1
[[0 0]
 [0 0]]
 
Array2
[[1 1]
 [1 1]]
 
-----------------
 
Joined by Axis 0 (4x2)
[[0 0]
 [0 0]
 [1 1]
 [1 1]]
 
Joined by Axis 1 (2x4)
[[0 0 1 1]
 [0 0 1 1]]


`Note: For Joining by Axis 0 (to the bottom), the second Dimension (Columns) must match`

In [119]:
array1 = np.array([[0, 0, 0], 
                   [0, 0, 0]])

array2 = np.array([[1, 1], 
                   [1, 1]])

print('Array1')
print(array1)
print(' ')
print('Array2')
print(array2)
print(' ')
print('-----------------')

# Will Raise an Error
array_joined = np.concatenate((array1, array2), axis=0)
print(' ')
print('Joined by Axis 0')
print(array_joined)

Array1
[[0 0 0]
 [0 0 0]]
 
Array2
[[1 1]
 [1 1]]
 
-----------------


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

`Note: For Joining by Axis 1 (to the right), the first Dimension (Rows) must match`

In [121]:
array1 = np.array([[0, 0], 
                   [0, 0], 
                   [0, 0]])

array2 = np.array([[1, 1], 
                   [1, 1]])

print('Array1')
print(array1)
print(' ')
print('Array2')
print(array2)
print(' ')
print('-----------------')

# Will Raise an Error
array_joined = np.concatenate((array1, array2), axis=1)
print(' ')
print('Joined by Axis 0')
print(array_joined)

Array1
[[0 0]
 [0 0]
 [0 0]]
 
Array2
[[1 1]
 [1 1]]
 
-----------------


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

Or use `hstack` and `vstack` instead

In [127]:
# Horizontal Stacking/Joining (hstack)
array1 = np.array([[0, 0, 0], 
                   [0, 0, 0]])

array2 = np.array([[1, 1], 
                   [1, 1]])

print('Array1')
print(array1)
print(' ')
print('Array2')
print(array2)
print(' ')
print('-----------------')

array_joined = np.hstack((array1, array2))
print(' ')
print('Stacked horizontally')
print(array_joined)

Array1
[[0 0 0]
 [0 0 0]]
 
Array2
[[1 1]
 [1 1]]
 
-----------------
 
Stacked horizontally
[[0 0 0 1 1]
 [0 0 0 1 1]]


In [133]:
# Vertical Stacking/Joining (vstack)
array1 = np.array([[0, 0], 
                   [0, 0], 
                   [0, 0]])

array2 = np.array([[1, 1], 
                   [1, 1]])

print('Array1')
print(array1)
print(' ')
print('Array2')
print(array2)
print(' ')
print('-----------------')

array_joined = np.vstack((array1, array2))
print(' ')
print('Stacked vertically')
print(array_joined)

Array1
[[0 0]
 [0 0]
 [0 0]]
 
Array2
[[1 1]
 [1 1]]
 
-----------------
 
Stacked vertically
[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


`Sorting` **1D-Array** using `sort`

In [245]:
array_int = np.array([3, 1, 5, 4, 2])
print(np.sort(array_int))

array_str = np.array(['Z', 'A', 'F', 'E', 'M'])
print(np.sort(array_str))

array_bool = np.array([True, False, False, True, False])
print(np.sort(array_bool))

[1 2 3 4 5]
['A' 'E' 'F' 'M' 'Z']
[False False False  True  True]


`Sorting` **2D-Array** using `sort(array, axis)`

In [273]:
array_str = np.array([['z', 'y', 'x', 'w', 'v'],
                      ['u', 't', 's', 'r', 'q'],
                      ['p', 'o', 'n', 'm', 'l'],
                      ['k', 'j', 'i', 'h', 'g'],
                      ['f', 'e', 'd', 'c', 'b'],
                      ['a', '+', '-', '#', '!']])

# Row-wise Sorting
print('Row-wise (axis=1)')
print(np.sort(array_str, axis=1))

# Column-wise Sorting
print(' ')
print('Column-wise (axis=0)')
print(np.sort(array_str, axis=0))

# Flattening (to 1D) and Sorting
print(' ')
print('Flattening and Sorting (axis=None)')
print(np.sort(array_str, axis=None))

Row-wise (axis=1)
[['v' 'w' 'x' 'y' 'z']
 ['q' 'r' 's' 't' 'u']
 ['l' 'm' 'n' 'o' 'p']
 ['g' 'h' 'i' 'j' 'k']
 ['b' 'c' 'd' 'e' 'f']
 ['!' '#' '+' '-' 'a']]
 
Column-wise (axis=0)
[['a' '+' '-' '#' '!']
 ['f' 'e' 'd' 'c' 'b']
 ['k' 'j' 'i' 'h' 'g']
 ['p' 'o' 'n' 'm' 'l']
 ['u' 't' 's' 'r' 'q']
 ['z' 'y' 'x' 'w' 'v']]
 
Flattening and Sorting (axis=None)
['!' '#' '+' '-' 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n'
 'o' 'p' 'q' 'r' 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']


`Searching` **1D-Array** using `where`

In [268]:
array1D = np.array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1])
print(array1D)

# Return Indices for Zero Elements
idxZero = np.where(array1D == 0)
print(' ')
print('Indices for Zero Elements')
print(idxZero)
print(type(idxZero))

[0 0 1 1 0 1 1 1 0 1]
 
Indices for Zero Elements
(array([0, 1, 4, 8]),)
<class 'tuple'>


In [355]:
print(array1D)

# Return Indices for Non-Zero Elements
idxNotZero = np.where(array1D != 0)
print('Indices for Non-Zero Elements')
print(idxNotZero)
print(type(idxNotZero))

[0 0 1 1 0 1 1 1 0 1]
Indices for Non-Zero Elements
(array([2, 3, 5, 6, 7, 9]),)
<class 'tuple'>


In [356]:
print(array1D)

# Change Values for Non-Zero Elements to Zero
array1D = np.where(array1D != 0, 0, array1D)
print(' ')
print('Array with changed Values')
print(array1D)

[0 0 1 1 0 1 1 1 0 1]
 
Array with changed Values
[0 0 0 0 0 0 0 0 0 0]


`Searching` **2D-Array** using `where`

In [357]:
array2D = np.array([[0, 0, 1, 0, 1],
                    [0, 1, 0, 1, 1],
                    [0, 0, 1, 1, 1],
                    [0, 1, 0, 0, 1]])
print(array2D)

# Return Indices for Zero Elements
idxZero = np.where(array2D == 0)
print(' ')
print('Indices for Zero Elements')
print(idxZero)
print(type(idxZero))

[[0 0 1 0 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [0 1 0 0 1]]
 
Indices for Zero Elements
(array([0, 0, 0, 1, 1, 2, 2, 3, 3, 3]), array([0, 1, 3, 0, 2, 0, 1, 0, 2, 3]))
<class 'tuple'>


In [358]:
print(array2D)

# Change Values for Zero Elements
array2D = np.where(array2D == 0, -1, array2D)
print(' ')
print('Array with changed Values')
print(array2D)

[[0 0 1 0 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [0 1 0 0 1]]
 
Array with changed Values
[[-1 -1  1 -1  1]
 [-1  1 -1  1  1]
 [-1 -1  1  1  1]
 [-1  1 -1 -1  1]]


In [359]:
# Multiple Conditions with '&'(AND)
# Note: Use () for each Condition

print(array2D)

# Change Values
array2D = np.where(
    (array2D < 0) & (array2D > -2), 
    0, array2D
)
print(' ')
print('Array with changed Values')
print(array2D)

[[-1 -1  1 -1  1]
 [-1  1 -1  1  1]
 [-1 -1  1  1  1]
 [-1  1 -1 -1  1]]
 
Array with changed Values
[[0 0 1 0 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [0 1 0 0 1]]


In [360]:
# Multiple Conditions with '|'(OR)
# Note: Use () for each Condition

print(array2D)

# Change Values
array2D = np.where(
    (array2D == 0) | (array2D == 1), 
    -1, array2D
)
print(' ')
print('Array with changed Values')
print(array2D)

[[0 0 1 0 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [0 1 0 0 1]]
 
Array with changed Values
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]


`Filtering` **1D-Array** using `Boolean Masking`

In [361]:
array1D = np.array([1, 2, 3, 4, 5])
print(array1D)

# Filter Values > 2
# -----------------------------
# Create Boolean Mask by Hand
bool_mask = np.array([False, False, True, True, True])
print(' ')
print('Boolean Mask')
print(bool_mask)
# -----------------------------
# Filter
print(' ')
print('Values filtered')
print(array1D[bool_mask])

[1 2 3 4 5]
 
Boolean Mask
[False False  True  True  True]
 
Values filtered
[3 4 5]


In [362]:
# Create Boolean Mask automatically
bool_mask = array1D > 2
print(bool_mask)

[False False  True  True  True]


In [363]:
# Filter Values > 2 directly
print(array1D[array1D > 2])

[3 4 5]


`Filtering` **2D-Array** using `Boolean Masking`

In [263]:
array2D = np.array([[0, 0, 1, 0, 1],
                    [0, 1, 0, 1, 1],
                    [0, 0, 1, 1, 1],
                    [0, 1, 0, 0, 1]])
print(array2D)

# Filter Zero Values
print(' ')
print('Values filtered')
print(array2D[array2D == 0])
# Count Zero Values
print(' ')
print('Number of Zero Values in array2D')
print(len(array2D[array2D == 0]))
# Print Boolean Mask
print(' ')
print('Boolean Mask')
print(array2D == 0)

[[0 0 1 0 1]
 [0 1 0 1 1]
 [0 0 1 1 1]
 [0 1 0 0 1]]
 
Values filtered
[0 0 0 0 0 0 0 0 0 0]
 
Number of Zero Values in array2D
10
 
Boolean Mask
[[ True  True False  True False]
 [ True False  True False False]
 [ True  True False False False]
 [ True False  True  True False]]


`Adding and Subtracting Arrays`

In [400]:
array1 = np.array([1, 2, 3])
print(array1)

array2 = np.array([1, 1, 1])
print(' ')
print(array2)

# Add 
array_new = array1 + array2
print(' ')
print('array1 + array2')
print(array_new)

# Subtract
array_new = array1 - 1
print(' ')
print('array1 - 1')
print(array_new)

[1 2 3]
 
[1 1 1]
 
array1 + array2
[2 3 4]
 
array1 - 1
[0 1 2]


`Multiplying and Dividing Arrays`

In [406]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(array1)

array2 = np.array([[1, 0, 0],
                   [0, 1, 0],
                   [0, 0, 1]])
print(' ')
print(array2)


# Multiply
array_new = array1 * array2
print(' ')
print('array1 * array2')
print(array_new)

# Divide
array_new = array1 / 10
print(' ')
print('array1 / 10')
print(array_new)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
 
[[1 0 0]
 [0 1 0]
 [0 0 1]]
 
array1 * array2
[[1 0 0]
 [0 5 0]
 [0 0 9]]
 
array1 / 10
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]
 [0.7 0.8 0.9]]


`Aggregation Functions on Arrays`

In [427]:
array = np.eye(10)
print(array)

# Aggregation
print(' ')
print('Minimum:',   array.min())
print('Maximum:',   array.max())
print('Sum:',       array.sum())
print('Product:',   array.prod())
print('Mean:',      array.mean())
print('Std. Dev.:', array.std())

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
 
Minimum: 0.0
Maximum: 1.0
Sum: 10.0
Product: 0.0
Mean: 0.1
Std. Dev.: 0.3


`Row-wise and Column-wise Aggregation` using `axis`

In [423]:
array = np.random.random((3, 3))
print(array)

# Axis 0 (column-wise)
print(' ')
print('Maximum per Col:', array.max(axis=0))

# Axis 1 (row-wise)
print(' ')
print('Maximum per Row:', array.max(axis=1))

[[0.45125267 0.88701172 0.77893656]
 [0.52022304 0.28595273 0.67857105]
 [0.56815443 0.85399331 0.26257491]]
 
 Maximum per Col: [0.56815443 0.88701172 0.77893656]
 
 Maximum per Row: [0.88701172 0.67857105 0.85399331]


`Unique Values of Arrays`

In [438]:
array = np.array([[0, 1, 0],
                  [2, 0, 0],
                  [0, 0, 3]])
print(array)

# Unique Values
print(' ')
print('Unique Values:', np.unique(array))

# Unique Values including Counts
print(' ')
print('Unique Values:', np.unique(array, return_counts=True))

# Number of Unique Values
print(' ')
print('Unique Values:', len(np.unique(array)))

[[0 1 0]
 [2 0 0]
 [0 0 3]]
 
Unique Values: [0 1 2 3]
 
Unique Values: (array([0, 1, 2, 3]), array([6, 1, 1, 1]))
 
Unique Values: 4


`Unique Values in certain Row or Column`

In [446]:
array = np.array([[0, 1, 0],
                  [2, 0, 0],
                  [0, 0, 3]])
print(array)

# Unique Values in first Row
print(' ')
print('Unique Values in first Row')
print(np.unique(array[0, :]))

# Unique Values in last Column
print(' ')
print('Unique Values in last Column')
print(np.unique(array[:, -1]))

[[0 1 0]
 [2 0 0]
 [0 0 3]]
 
Unique Values in first Row
[0 1]
 
Unique Values in last Column
[0 3]


`Random Numbers and Arrays`

In [518]:
# Random Integer between 0 and x
x = 10
number = np.random.randint(x)
print(number)

2


In [600]:
# 1D-Array with Random Integers
array1D = np.random.randint(10, size=(5))
print(array1D)

[4 9 3 9 1]


In [601]:
# 2D-Array with Random Integers
array2D = np.random.randint(10, size=(5, 5))
print(array2D)

[[2 6 5 0 0]
 [4 9 4 3 6]
 [8 0 4 3 4]
 [6 2 0 1 6]
 [2 6 4 7 5]]


In [625]:
# Random Floating Point Number between 0 and 1
number = np.random.rand()
print(number)

0.4764546327816017


In [658]:
# 1D-Array with Random Point Numbers
array1D = np.random.rand(5)
print(array1D)

[0.03842639 0.69751709 0.99127284 0.92042042 0.57344562]


In [676]:
# 2D-Array with Random Point Numbers
array2D = np.random.rand(5, 5)
print(array2D)

[[0.10861627 0.72889035 0.91220604 0.51115726 0.30328698]
 [0.23136927 0.47025751 0.82213693 0.40896021 0.48180145]
 [0.36666391 0.99323575 0.16998274 0.68536569 0.67028464]
 [0.34122678 0.00742908 0.56462685 0.00568169 0.80796748]
 [0.45920519 0.6970879  0.03656475 0.48121534 0.23199349]]


In [691]:
# Randomly choose a Number from an Array of Numbers
array = [1, 2, 3, 4, 5]
print(np.random.choice(array))

4


In [748]:
# Randomly choose an Array of Numbers from an Array of Numbers (i.e. Lottozahlen)
lotto_numbers = np.arange(1, 49+1)
print(lotto_numbers)

draw = np.random.choice(lotto_numbers, size=(6), replace=False)
print(' ')
print(np.sort(draw))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
 
[ 6 15 21 26 36 45]
